### ISSUE TITLE
Documentation is incomplete

### ISSUE THREAD

**Issue by RobertoGongora** [timcreative/material-kit-pro#5]
I was trying to read the docs about transparent navbars, and when clicking on the provided link to see more detailed examples on how to implement them I was lead to a 404 page, specifically: /HTML/navbar-transparent.html

**Comment by alexandru-paduraru** [comment]
@RobertoGongora thank you for using our product. We've checked and you're right, there is an issue with a missing file for the navbar-transparent. We are preparing an update that should come this week and that will be fixed. Please let us know what information you need about the transparent navbar and we will help you.

Best,
Alex

**Comment by RobertoGongora** [comment]
Thanks! I was having trouble with the positioning of the navbar, but I inspected some of the other implementations and applied the same classes and it just worked, including the coloring on scroll and everything. 

Keep up the good work!

**Comment by alexandru-paduraru** [comment]
@RobertoGongora glad that you found the solution fast. Don't hesitate to contact us if you need any further assistance.

Best,
Alex

**Comment by elvnthaus** [comment]
For anyone wondering, if you need to change when the navbar becomes transparent you can adjust the VALUE found on line 25 of the material-kit.js file here:
```
  scroll_distance = $navbar.attr('color-on-scroll') || VALUE;
```
